"""Reconstruct Figure 2 inside the supplied three-column PowerPoint template.

Keeps the original ribbons, column frames, pictograms, example cards, and
choice/timing comparison layout. All revised labels and connectors are native
PowerPoint objects. No experimental values are generated by this script.
Export the result with LibreOffice/PowerPoint, then use the resulting vector PDF.
"""
from pathlib import Path
from copy import deepcopy
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE, MSO_CONNECTOR
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR, MSO_AUTO_SIZE
from lxml import etree

ROOT=Path(__file__).resolve().parents[1]
SOURCE=ROOT/'figures/template/figure2_supplied_method.pptx'
OUT=ROOT/'figures/narrative/figure2_method_template.pptx'
p=Presentation(SOURCE);s=p.slides[0]
original={sh.shape_id:sh for sh in s.shapes}
BLUE='0867AE';GREEN='138934';ORANGE='EF871F';INK='08164F'
PALE_BLUE='E4F3FC';PALE_GREEN='E9F6E9';PALE_ORANGE='FFF4E5'
A='http://schemas.openxmlformats.org/drawingml/2006/main'

# Retain real template objects rather than making a flat background screenshot.
keep=set(range(2,14))|{14,16,18,20,22,44,72}|set(range(86,107))
keep|={248,249,251,252,253,254,910,918,920,882,884,888,890}
keep|=set(range(408,425))|set(range(441,449))
keep|={511,513,514,515,516,523,524,555,947,945,949,906,908,912,914}
keep -= {94,101,415}
for sh in list(s.shapes):
    if sh.shape_id not in keep:s.shapes._spTree.remove(sh._element)
# The legacy equation title is an AlternateContent node, not exposed by python-pptx.
for node in list(s.shapes._spTree):
    if etree.QName(node).localname == 'AlternateContent':
        s.shapes._spTree.remove(node)

def remove(ids):
    for sh in list(s.shapes):
        if sh.shape_id in ids:s.shapes._spTree.remove(sh._element)

def style_text(sh,text,size=20,bold=True,color=INK,align=PP_ALIGN.CENTER):
    tf=sh.text_frame;tf.clear();tf.word_wrap=False;tf.auto_size=MSO_AUTO_SIZE.NONE
    tf.margin_left=tf.margin_right=Pt(1);tf.margin_top=tf.margin_bottom=Pt(0)
    tf.vertical_anchor=MSO_ANCHOR.MIDDLE
    for i,line in enumerate(text.split('\n')):
        par=tf.paragraphs[0] if i==0 else tf.add_paragraph()
        par.alignment=align;par.space_before=par.space_after=Pt(0)
        par.line_spacing=1.0
        r=par.add_run();r.text=line;r.font.name='Roboto Condensed'
        r.font.size=Pt(size);r.font.bold=bold;r.font.color.rgb=RGBColor.from_string(color)
    sh.name='Figure 2 | '+text.replace('\n',' / ')
    return sh

def text(txt,x,y,w,h,size=20,bold=True,color=INK,align=PP_ALIGN.CENTER):
    sh=s.shapes.add_textbox(Inches(x),Inches(y),Inches(w),Inches(h))
    return style_text(sh,txt,size,bold,color,align)

def box(txt,x,y,w,h,fill=PALE_BLUE,line=BLUE,size=20,bold=True):
    sh=s.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE,Inches(x),Inches(y),Inches(w),Inches(h))
    sh.name='Figure 2 | container'
    sh.fill.solid();sh.fill.fore_color.rgb=RGBColor.from_string(fill)
    sh.line.color.rgb=RGBColor.from_string(line);sh.line.width=Pt(1.3)
    try:sh.adjustments[0]=.045
    except Exception:pass
    for e in sh._element.findall(f'.//{{{A}}}effectRef'):e.set('idx','0')
    if txt:text(txt,x+.04,y+.02,w-.08,h-.04,size,bold)
    return sh

def conn(points,col=BLUE,width=1.8,arrow=True):
    for i,((x1,y1),(x2,y2)) in enumerate(zip(points[:-1],points[1:])):
        sh=s.shapes.add_connector(MSO_CONNECTOR.STRAIGHT,Inches(x1),Inches(y1),Inches(x2),Inches(y2))
        sh.name='Figure 2 | relationship';sh.line.color.rgb=RGBColor.from_string(col);sh.line.width=Pt(width)
        if arrow and i==len(points)-2:
            e=etree.SubElement(sh._element.spPr.find(f'{{{A}}}ln'),f'{{{A}}}tailEnd')
            e.set('type','triangle');e.set('w','med');e.set('len','med')

def icon(ident,x,y,w=None,h=None):
    e=deepcopy(original[ident]._element)
    for cn in e.findall('.//{http://schemas.openxmlformats.org/presentationml/2006/main}cNvPr'):
        cn.set('id',str(s.shapes._next_shape_id));cn.set('name','Retained template pictogram')
    s.shapes._spTree.insert_element_before(e,'p:extLst')
    sh=s.shapes[-1];sh.left=Inches(x);sh.top=Inches(y)
    if w is not None:sh.width=Inches(w)
    if h is not None:sh.height=Inches(h)
    return sh

# Original blue/green/orange ribbon backgrounds and chevrons are unchanged.
headers={8:('(a) Behavioral Supervision',26),9:('State predictions and scenario responses',19),
         10:('(b) Traveler Models',26),11:('Joint and separate choice–timing specifications',19),
         12:('(c) Demand Simulation',26),13:('From predicted choices to simulated trips',19)}
for ident,(label,size) in headers.items():
    sh=original[ident]
    if ident in (8,10,12):
        sh.left=Inches({8:.35,10:5.87,12:11.49}[ident]);sh.width=Inches(5.0)
    style_text(sh,label,size,True if ident in (8,10,12) else False,'FFFFFF')

# (a) The four cards and their actual template graphics stay in their original locations.
text('Behavioral contrasts',.30,.99,2.50,.46,22)
text('Scenario contrasts',.40,1.60,2.20,.29,19)
text('Single and joint changes',.40,2.39,2.18,.23,18,False)
text('Traveler contrasts†',.40,2.80,2.20,.29,19)
text('Between travelers',.42,3.61,2.16,.24,18,False)
text('Context–attribute',.40,3.98,2.20,.29,19)
text('Base / joint\nContext / attributes',.39,4.75,2.23,.45,18,False)
text('PT supply profiles',.40,5.34,2.20,.29,19)
text('Access · wait · transfers',.38,6.24,2.23,.30,18,False)
# Teacher target area: replace the request/validation lifecycle with the target objects.
box('',3.07,1.25,2.16,5.32,fill='FFF8E9',line=ORANGE)
text('LLM Teacher',3.15,1.34,2.00,.38,22)
icon(937,3.83,1.91,.65,.62)
text('Repeated\nelicitation',3.17,2.83,1.96,.72,21)
conn([(4.15,2.56),(4.15,2.77)])
conn([(4.15,3.60),(4.15,3.82)])
box('',3.21,3.88,1.88,2.49,fill='FFF2D9',line=ORANGE)
text('Teacher targets',3.25,3.99,1.80,.34,20)
text('pₜ(x)',3.29,4.50,1.72,.40,27,False)
text('τₜ(x)',3.29,5.06,1.72,.40,27,False)
text('Δpₜ',3.29,5.62,1.72,.40,27,False)
conn([(4.15,6.58),(4.15,7.04)])
conn([(2.72,6.72),(2.72,7.04)])
# The bottom estimation strip remains in place, without gear/update/checkpoint graphics.
box('',.18,7.10,5.21,2.10,fill='F0F8FE',line='58BFF1')
text('Estimation objectives',.36,7.24,4.83,.36,22)
for label,x,w in [('State\nfidelity',.31,1.56),('Response\nfidelity',1.97,1.56),('Departure\nfit',3.63,1.61)]:
    box(label,x,7.80,w,.62,fill='FFFFFF',line='58BFF1',size=20)
conn([(2.78,8.43),(2.78,8.66)])
box('Model estimation',1.06,8.71,3.44,.35,fill=PALE_BLUE,line=BLUE,size=21)
# The dagger is explained in the paper caption and slide notes to keep the cards readable.

# (b) Preserve the original input blocks, pictograms, and two-output chart/axis.
remove({253,254,411,414})
text('Traveler state',6.89,.96,2.93,.31,21)
text('Traveler and trip',5.99,1.43,2.18,.30,20)
text('Modes and service',8.48,1.43,2.35,.30,19)
text('Traveler / trip attributes',5.99,2.41,2.19,.26,18,False)
text('Service attributes',8.51,2.41,2.26,.26,18,False)
# Two specifications in the same original center-column geometry.
box('',5.87,3.16,2.42,3.15,fill='F5FAFD',line=BLUE)
box('',8.43,3.16,2.42,3.15,fill='F4FAF2',line=GREEN)
text('Joint neural model',5.94,3.23,2.28,.34,21)
text('Separate models',8.50,3.23,2.28,.34,21)
conn([(8.35,2.86),(8.35,3.00),(7.08,3.00),(7.08,3.16)],GREEN)
conn([(8.35,3.00),(9.64,3.00),(9.64,3.16)],GREEN)
box('Shared\nrepresentation',6.02,3.83,2.12,.62,PALE_BLUE,BLUE,19)
conn([(7.08,3.58),(7.08,3.82)])
conn([(7.08,4.45),(7.08,4.58),(6.56,4.58),(6.56,4.77)])
conn([(7.08,4.58),(7.64,4.58),(7.64,4.77)])
box('Choice\nutilities',6.01,4.78,1.08,.62,PALE_BLUE,BLUE,19)
box('Departure\npredictor',7.17,4.78,1.00,.62,PALE_GREEN,GREEN,18)
conn([(6.55,5.40),(6.55,5.60)])
conn([(7.67,5.40),(7.67,5.60)],GREEN)
box('pₛ(x)',6.01,5.60,1.08,.50,PALE_BLUE,BLUE,25,False)
box('τₛ(x)',7.17,5.60,1.00,.50,PALE_GREEN,GREEN,25,False)
conn([(9.64,3.58),(9.64,3.71),(9.08,3.71),(9.08,3.84)],GREEN)
conn([(9.64,3.71),(10.21,3.71),(10.21,3.84)],GREEN)
box('MNL-S\nlinear\nutilities',8.53,3.85,1.09,1.34,PALE_BLUE,BLUE,19)
box('Neural\ndeparture\npredictor',9.68,3.85,1.09,1.34,PALE_GREEN,GREEN,18)
conn([(9.08,5.19),(9.08,5.60)])
conn([(10.22,5.19),(10.22,5.60)],GREEN)
box('pₛ(x)',8.53,5.60,1.09,.50,PALE_BLUE,BLUE,25,False)
box('τₛ(x)',9.68,5.60,1.09,.50,PALE_GREEN,GREEN,25,False)
# Converging arrows denote the same output type, not averaged model predictions.
for x in (6.55,7.67,9.08,10.22):conn([(x,6.10),(x,6.43)],GREEN,arrow=False)
conn([(6.55,6.43),(10.22,6.43)],GREEN,arrow=False)
conn([(8.35,6.43),(8.35,6.64)],GREEN)
text('Behavioral predictions',6.77,6.74,3.25,.29,21)
text('Mode probabilities',5.97,7.16,2.19,.28,18)
text('Departure shift τₛ',8.52,7.16,2.18,.30,18)
# Bottom strip is explanatory, not an internal lifecycle.
text('Common outcomes,\ndifferent specifications',5.94,8.55,4.82,.58,22,True,GREEN)
conn([(4.51,8.89),(5.57,8.89)],BLUE)

# (c) Keep original population/network/timetable imagery at the top.
remove({515,523,524,555,947})
text('Simulation inputs',11.49,.99,4.68,.29,22,True,'AF3B00')
text('Travelers and trips',11.56,1.34,2.21,.31,20)
text('Population\nOD pairs',12.63,1.77,1.15,.57,18,False)
text('Network and timetable',14.04,1.34,2.28,.31,19)
text('Network',14.08,2.25,1.14,.23,18,False)
text('Timetable',15.20,2.25,1.08,.23,18,False)
conn([(12.67,2.55),(12.67,2.73),(15.17,2.73),(15.17,2.55)],BLUE,arrow=False)
conn([(13.91,2.73),(13.91,2.98)],BLUE)
box('Level of service and route availability',11.42,2.98,5.01,.66,PALE_ORANGE,ORANGE,21)
conn([(13.91,3.64),(13.91,3.97)],BLUE)
box('',11.77,3.98,4.32,.66,PALE_BLUE,BLUE)
icon(620,12.02,4.10,.43,.43)
text('Behavioral prediction: pₛ, τₛ',12.54,4.08,3.42,.45,21)
# Link the center's common predictions to the simulation prediction step.
conn([(10.99,7.49),(11.14,7.49),(11.14,4.31),(11.76,4.31)],GREEN)
conn([(13.91,4.65),(13.91,4.93)],BLUE)
box('',11.43,4.94,5.00,.99,PALE_ORANGE,ORANGE)
text('Mode assignment',11.53,4.99,4.78,.30,22)
text('Deterministic',11.48,5.40,1.48,.39,18)
text('Stochastic',13.08,5.40,1.27,.39,18)
text('Feasibility-\nconstrained',14.55,5.31,1.78,.55,18)
conn([(13.91,5.94),(13.91,6.15)],BLUE)
box('OD and adjusted departure',11.99,6.16,3.83,.39,'FFFFFF',ORANGE,20)
conn([(13.91,6.56),(13.91,6.81)],BLUE)
box('',12.00,6.82,4.06,.46,'FFFFFF',ORANGE)
icon(959,12.18,6.81,.46,.46)
text('Multimodal routing',12.75,6.87,3.04,.32,21)
conn([(13.90,7.29),(13.90,7.36),(12.63,7.36),(12.63,7.46)],BLUE)
box('',11.60,7.46,2.05,.49,'FFFFFF',ORANGE)
icon(961,11.72,7.51,.36,.36)
text('Travel plans',12.11,7.54,1.43,.32,21)
conn([(13.66,7.69),(14.40,7.69)],BLUE)
box('',14.41,7.46,1.98,.49,'FFFFFF',ORANGE)
icon(763,14.58,7.50,.37,.39)
text('MATSim',15.08,7.54,1.11,.30,21)
conn([(15.37,7.96),(15.37,8.15)],BLUE)
box('',11.32,8.17,5.20,1.01,PALE_ORANGE,ORANGE)
for x,w,title,sub in [(11.44,1.40,'Mode use','PT use'),(12.94,1.76,'Activity','Boardings · VKT'),(14.80,1.58,'Journeys','Time · completion')]:
    box('',x,8.28,w,.58,'FFFFFF',ORANGE)
    text(title,x+.03,8.30,w-.06,.23,18)
    text(sub,x+.03,8.60,w-.06,.21,16,False)
text('Response gap: simulated − predicted',11.49,8.94,4.87,.23,19,False,'AF3B00')

s.notes_slide.notes_text_frame.text=(
 'Edited directly from the supplied Figure 2 PPTX template. Original three-column ribbons, frames, '
 'example artwork, traveler/mode/network pictograms and the joint/separate architecture comparison are retained. '
 'Teacher targets are p_T(x), tau_T(x), and the finite scenario response Delta p_T. '
 'Dagger: between-traveler contrasts are additional supervision for SA-Student, not a shared auxiliary loss '
 'in the four-objective controlled comparison. The neural timing illustration is one of three independent timing specifications. '
 'Probabilities are normalized over behaviorally available alternatives; search-defined feasibility is applied separately. '
 'The last assignment policy is stochastic after feasibility adjustment. No online Teacher, survey training input, '
 'or simulation-to-training feedback is shown. The diagram does not specify the undocumented zero-feasible-mass case '
 'or claim that all fitted models share an identical training history. All new text and diagrams are editable PowerPoint objects.'
)
# Ensure unique identifiers even in retained group pictograms.
ids=[]
for sh in s.shapes:
    for e in sh._element.findall('.//{http://schemas.openxmlformats.org/presentationml/2006/main}cNvPr'):
        ids.append(e)
for idx,e in enumerate(ids,2):e.set('id',str(idx))
OUT.parent.mkdir(parents=True,exist_ok=True);p.save(OUT)
print(OUT)
print('Original shapes:',len(original),'Revised shapes:',len(s.shapes))
